pipeline {
    agent { label 'nodejs' }
    stages {
        stage('Unit Test') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                dir ('exchange-cli') {
                    sh 'npm run build'

                }
            }
        }
    }
}